#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Guided Setup is operator-driven and resumable. It never edits Workspace
# credential fields and never runs a migration without an accepted backup.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP="${APP:-http://127.0.0.1:4317}"
WORKSPACE_DIR="${WORKSPACE_DIR:-$REPO_ROOT/workspace}"
# The reusable wizard library supplies ".env" before these stages run.
[[ "$ENV_FILE" == ".env" ]] && ENV_FILE="$REPO_ROOT/.env"
BACKUP_DESTINATION="${BACKUP_DESTINATION:-$HOME/.local/share/chief-of-staff-demo/guided-setup-backup}"
BACKUP_RESULT="${BACKUP_RESULT:-$BACKUP_DESTINATION/result.json}"
STOPPED_CONTAINER="${STOPPED_CONTAINER:-chief-of-staff-demo-app-1}"
MIGRATION_SCRIPT="$REPO_ROOT/scripts/migrate-installation-credentials.mts"

TOTAL_STAGES=10

banner "Chief of Staff — Guided Setup"

for _tool in pnpm docker curl jq python3; do
  command -v "$_tool" >/dev/null 2>&1 || { warn "$_tool is required"; exit 1; }
done
[[ -f "$MIGRATION_SCRIPT" ]] || { warn "migration command is missing"; exit 1; }
for _path in "$WORKSPACE_DIR" "$ENV_FILE" "$BACKUP_RESULT"; do
  [[ "$_path" = /* ]] || { warn "Guided Setup paths must be absolute: $_path"; exit 1; }
done
mkdir -p "$(dirname "$ENV_FILE")"
if [[ ! -f "$WORKSPACE_DIR/config.json" ]]; then
  if [[ -d "$WORKSPACE_DIR" && -n "$(ls -A "$WORKSPACE_DIR")" ]]; then
    warn "Workspace has files but no config.json; inspect it before setup"
    exit 1
  fi
  FRESH_WORKSPACE=true
else
  FRESH_WORKSPACE=false
fi

api_get() {
  _API_BODY="$(curl -fsS --max-time 10 "$APP$1" 2>/dev/null || true)"
}

wait_for_health() {
  local seconds="${1:-60}"
  local elapsed=0
  while (( elapsed < seconds )); do
    if curl -fsS --max-time 3 "$APP/api/health" >/dev/null 2>&1; then return 0; fi
    sleep 2
    elapsed=$((elapsed + 2))
  done
  return 1
}

migration_check() {
  pnpm exec tsx "$MIGRATION_SCRIPT" check \
    --workspace "$WORKSPACE_DIR" --env "$ENV_FILE" --backup-result "$BACKUP_RESULT"
}

migration_apply() {
  pnpm exec tsx "$MIGRATION_SCRIPT" apply \
    --workspace "$WORKSPACE_DIR" --env "$ENV_FILE" --backup-result "$BACKUP_RESULT"
}

# ── 1 · Preflight and paths ────────────────────────────────────────────────
stage "Preflight and paths"
say "This local setup provisions installation credentials once for this installation."
say "Workspace: $WORKSPACE_DIR"
say "Installation environment: $ENV_FILE"
say "The Workspace keeps provider/model choices, Google consent, and records; it does not keep installation secret values."
confirm "Continue with the local Guided Setup?" || { warn "setup cancelled"; exit 1; }

# ── 2 · Required Workspace backup ─────────────────────────────────────────
stage "Required Workspace backup"
if [[ "$FRESH_WORKSPACE" == true ]]; then
  say "No Workspace records exist yet; there is nothing to back up or migrate."
else
  say "The app must be stopped before the private backup is captured."
  say "Choose a new private backup destination; it must not be inside the Workspace or repository."
  step "Stop the app and any other Workspace writer, then press Enter."
  pause "App stopped and all other writers are quiet"
  step "Capture the Workspace backup (the command verifies two isolated restorations)."
  if [[ -f "$BACKUP_RESULT" ]]; then
    say "Existing backup result found. Stage 3 verifies it before any migration."
  elif [[ -e "$BACKUP_DESTINATION" ]]; then
    warn "backup destination exists without a result; choose a new BACKUP_DESTINATION and resume"
    exit 1
  else
    pnpm exec tsx "$REPO_ROOT/scripts/workspace-backup.mts" capture \
      "$WORKSPACE_DIR" "$BACKUP_DESTINATION" "$REPO_ROOT" "$STOPPED_CONTAINER" || {
      warn "backup failed; no credential migration was attempted"
      exit 1
    }
  fi
  [[ -f "$BACKUP_RESULT" ]] || { warn "backup result is missing; setup stops safely"; exit 1; }
  say "Accepted backup evidence is available. Keep it private for recovery."
fi

# ── 3 · Check migration and confirm ───────────────────────────────────────
stage "Check migration and confirm"
say "The read-only check verifies the accepted backup and reports whether legacy fields need transfer."
if [[ "$FRESH_WORKSPACE" == true ]]; then
  say "Fresh installation: no legacy credentials require transfer."
else
  migration_check || { warn "migration check failed; source and destination remain unchanged"; exit 1; }
fi
confirm "Continue to provision the checked installation values?" || {
  warn "setup paused before any migration; resume later"
  exit 1
}

# ── 4 · Installation Google client ────────────────────────────────────────
stage "Installation Google client"
LEGACY_GOOGLE=false
if [[ "$FRESH_WORKSPACE" == false ]] && jq -e '.google.clientId and .google.clientSecret' "$WORKSPACE_DIR/config.json" >/dev/null; then
  LEGACY_GOOGLE=true
fi
if [[ "$LEGACY_GOOGLE" == true ]]; then
  say "The existing Workspace Google client will transfer at stage 6 without re-entry."
else
  for credential in GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET; do
    if [[ -n "${!credential:-}" || -n "$(_existing "$credential" || true)" ]]; then
      say "$credential is already configured; keeping it."
      continue
    fi
    step "Prepare the installation Google OAuth client in Google Cloud."
    open_url "https://console.cloud.google.com/apis/credentials"
    ask_secret "$credential" "Installation $credential:"
    [[ -n "${!credential}" ]] || { warn "$credential is required"; exit 1; }
    write_env "$credential" "${!credential}"
  done
fi

# ── 5 · Installation provider key ─────────────────────────────────────────
stage "Installation provider key"
step "Choose one installed cloud provider, or choose Ollama for a local model."
say "Cloud keys are provider-specific; Ollama needs no installation key."
CURRENT_PROVIDER="$(jq -r '.provider // empty' "$WORKSPACE_DIR/config.json" 2>/dev/null || true)"
LEGACY_PROVIDER_KEY=false
if [[ "$FRESH_WORKSPACE" == false ]] && jq -e '.apiKey | type == "string" and length > 0' "$WORKSPACE_DIR/config.json" >/dev/null; then
  LEGACY_PROVIDER_KEY=true
fi
if [[ "$LEGACY_PROVIDER_KEY" == true ]]; then
  PROVIDER="$CURRENT_PROVIDER"
  say "The existing $PROVIDER Workspace key will transfer without re-entry. Change Provider Choice after migration."
else
  [[ -n "$CURRENT_PROVIDER" ]] && say "Current Workspace provider: $CURRENT_PROVIDER"
  ask PROVIDER "Provider (openrouter|openai|anthropic|gemini|ollama${CURRENT_PROVIDER:+ [Enter keeps $CURRENT_PROVIDER]}):"
  [[ -z "$PROVIDER" && -n "$CURRENT_PROVIDER" ]] && PROVIDER="$CURRENT_PROVIDER"
fi
case "$PROVIDER" in
    openrouter|openai|anthropic|gemini)
      case "$PROVIDER" in
        openrouter) provider_env="OPENROUTER_API_KEY"; open_url "https://openrouter.ai/keys" ;;
        openai) provider_env="OPENAI_API_KEY"; open_url "https://platform.openai.com/api-keys" ;;
        anthropic) provider_env="ANTHROPIC_API_KEY"; open_url "https://console.anthropic.com/settings/keys" ;;
        gemini) provider_env="GEMINI_API_KEY"; open_url "https://aistudio.google.com/apikey" ;;
      esac
      if [[ "$LEGACY_PROVIDER_KEY" == true ]]; then
        say "$provider_env will be transferred at stage 6."
      elif [[ -n "${!provider_env:-}" || -n "$(_existing "$provider_env" || true)" ]]; then
        say "$provider_env is already configured; keeping it."
      else
        ask_secret "$provider_env" "Installation API key for $PROVIDER:"
        [[ -n "${!provider_env}" ]] || { warn "$provider_env is required"; exit 1; }
        write_env "$provider_env" "${!provider_env}"
      fi
      ;;
  ollama) say "Ollama selected; no installation key is required." ;;
  *) warn "choose a listed provider"; exit 1 ;;
esac

# ── 6 · Apply migration and verify destination ───────────────────────────
stage "Apply migration and verify destination"
if [[ "$FRESH_WORKSPACE" == true ]]; then
  say "Fresh installation: no Workspace credential fields need removal."
else
  say "The app remains stopped. The command verifies exact values and mode 600 before removing source fields."
  confirm "Run the backup-gated credential migration now?" || { warn "migration not applied"; exit 1; }
  migration_apply || { warn "migration failed; retain the backup and inspect the recovery state"; exit 1; }
  say "Migration applied. The backup remains available for recovery."
fi

# ── 7 · Restart installation ──────────────────────────────────────────────
stage "Restart installation"
step "Start the same app container so it loads the installation environment."
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"
docker compose -f "$REPO_ROOT/docker-compose.yml" --env-file "$ENV_FILE" up -d --force-recreate app
wait_for_health 90 || { warn "app did not become healthy; keep the backup and resume"; exit 1; }
api_get /api/config.installation
printf '%s' "$_API_BODY" | jq -e --arg provider "$PROVIDER" \
  '.googleClient.state == "configured" and ($provider == "ollama" or .providerKeys[$provider].state == "configured")' >/dev/null || {
  warn "effective installation credentials are still missing; resume after provisioning"
  exit 1
}
say "Installation status is Configured/Missing/Not required only; no values are returned."

# ── 8 · Owner Google consent ──────────────────────────────────────────────
stage "Owner Google consent"
open_url "$APP/settings#group-google"
step "Sign in with the Google account that owns this Workspace and grant the requested permissions."
step "Return here after the app reports Connected. The installation client is shared; consent and refresh tokens stay in this Workspace."
pause "Google consent completed for this Workspace"
api_get /api/google/status
printf '%s' "$_API_BODY" | jq -e '.state == "connected"' >/dev/null || {
  warn "Google consent is not connected yet; resume when the owner has completed it"
  exit 1
}

# ── 9 · Provider, model, and Transcript Intake ───────────────────────────
stage "Provider, model, and Transcript Intake"
open_url "$APP/settings#api-key"
step "Confirm the provider and model in Settings. Only providers with an installed key, or Ollama, are selectable."
step "Choose the transcript Drive folder, enable Drive polling, and allow the app to read and process that folder."
step "Use the selected Google Drive folder and its existing intake controls; no manual upload step is part of this path."
pause "Provider, model, folder, polling, and consent are saved"
api_get "/api/migration/status?goal=meetings"
printf '%s' "$_API_BODY" | jq -e '.onboarding.complete == true' >/dev/null || {
  warn "Meeting prerequisites are unfinished; follow the five controls and resume"
  exit 1
}

# ── 10 · Verify the first result ─────────────────────────────────────────
stage "Verify the first result"
api_get "/api/migration/status?goal=meetings"
say "Meeting setup status: $(printf '%s' "$_API_BODY" | jq -r '.onboarding.complete // false')"
api_get /api/meetings/workspace
say "Meeting Intake status: $(printf '%s' "$_API_BODY" | jq -r '.intakeReadiness.verdict // "unavailable"')"
step "Open Meeting Wizard and follow the next truthful Transcript Intake action."
open_url "$APP/meetings"
if ! printf '%s' "$_API_BODY" | jq -e \
  '[.today[]?, .recent[]?, .upcoming[]?] | any(.debrief.status == "ready")' >/dev/null; then
  say "Meeting setup is ready, but the first Debrief is still waiting for a Transcript and extraction."
  say "Use the selected Drive folder and Sync now, then re-run this stage to verify the result."
  exit 0
fi

finish
