#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# This app keeps every value in workspace/config.json through its own HTTP
# API (there is no .env and CI holds no secrets), so the stages below capture
# with ask/ask_secret and persist with curl against the running app.

APP="${APP:-http://127.0.0.1:4317}"
_API_BODY=""
_API_CODE=0

# api METHOD PATH [JSON_BODY] — stores response in _API_BODY, status in _API_CODE.
api() {
  _API_BODY=""
  _API_CODE=0
  local method="$1" path="$2" body="${3:-}" out
  local curl_args=(-sS --max-time 120 -X "$method" "$APP$path" -H 'Content-Type: application/json' -w $'\n%{http_code}')
  [[ -n "$body" ]] && curl_args+=(-d "$body")
  if ! out="$(curl "${curl_args[@]}")"; then
    _API_CODE="000"
    return 1
  fi
  _API_CODE="${out##*$'\n'}"
  _API_BODY="${out%$'\n'*}"
}

# api_jq 'filter' — run a jq filter over the last response body.
api_jq() {
  printf '%s' "$_API_BODY" | jq -r "$1"
}

# load_config — GET /api/config into _API_BODY, warning on transport failure.
load_config() {
  if ! api GET /api/config; then
    warn "could not read config from $APP"
    return 1
  fi
}

# wait_health SECONDS — poll /api/health until ok.
wait_health() {
  local deadline=$(( $(date +%s) + $1 ))
  until curl -fsS --max-time 3 "$APP/api/health" >/dev/null 2>&1; do
    if (( $(date +%s) > deadline )); then return 1; fi
    printf '.'
    sleep 5
  done
  printf '\n'
}

TOTAL_STAGES=12

banner "Chief of Staff — full setup"

[[ -f docker-compose.yml ]] || { warn "run this from the repo root (docker-compose.yml not found)"; exit 1; }
for _tool in curl jq docker; do
  command -v "$_tool" >/dev/null 2>&1 || { warn "$_tool is required"; exit 1; }
done

# ── 1 · Bring the app up ──────────────────────────────────────────────────
stage "Bring-up"
if curl -fsS --max-time 3 "$APP/api/health" >/dev/null 2>&1; then
  say "App is already running at $APP — nothing to do."
else
  if ! command -v docker >/dev/null 2>&1 || ! docker info >/dev/null 2>&1; then
    step "Start Docker Desktop and wait for the whale in the menu bar to stop animating."
    open_url "https://www.docker.com/products/docker-desktop/"
    pause "Press Enter once Docker is running…"
  fi
  say "Building and starting the app (first run takes a few minutes)…"
  docker compose up -d --build
  say "Waiting for the app to become healthy"
  if ! wait_health 600; then
    warn "app did not become healthy — check 'docker compose logs app', then re-run this wizard."
    exit 1
  fi
  say "App is healthy at $APP"
fi

# ── 2 · Extraction provider (LLM) ─────────────────────────────────────────
stage "Extraction provider"
load_config
CUR_PROVIDER="$(api_jq '.config.provider')"
CUR_MODEL="$(api_jq '.config.model')"
CUR_KEY_SET="$(api_jq '.config.apiKey.set')"
CUR_KEY_HINT="$(api_jq '.config.apiKey.hint')"
say "Current: provider=$CUR_PROVIDER model=$CUR_MODEL api key=$( [[ "$CUR_KEY_SET" == "true" ]] && printf 'set (…%s)' "$CUR_KEY_HINT" || printf 'unset' )"
step "Create an API key on the provider's dashboard (it pays for the calls)."
ask PROVIDER "Provider (openai|anthropic|openrouter|gemini|ollama — OpenRouter is the default; mock exists only in test/demo mode):"
[[ -z "$PROVIDER" ]] && PROVIDER="$CUR_PROVIDER"
ask MODEL "Model id:"
[[ -z "$MODEL" ]] && MODEL="$CUR_MODEL"
API_KEY=""
if [[ "$CUR_KEY_SET" != "true" ]]; then
  ask_secret PROVIDER_API_KEY "Paste the provider API key:"
  API_KEY="$PROVIDER_API_KEY"
elif confirm "Replace the stored API key?"; then
  ask_secret PROVIDER_API_KEY "Paste the new provider API key:"
  API_KEY="$PROVIDER_API_KEY"
fi
body=$(jq -n --arg p "$PROVIDER" --arg m "$MODEL" --arg k "$API_KEY" \
  '{provider: $p, model: $m} + (if $k == "" then {} else {apiKey: $k} end)')
api PUT /api/config "$body"
if [[ "$_API_CODE" == "200" ]]; then
  load_config
  say "Saved: provider=$(api_jq '.config.provider') model=$(api_jq '.config.model') key hint …$(api_jq '.config.apiKey.hint')"
else
  warn "config save failed (HTTP $_API_CODE): $(api_jq '.error // empty')"
fi

# ── 3 · Google OAuth client ───────────────────────────────────────────────
stage "Google OAuth client"
load_config
if [[ "$(api_jq '.config.google.clientSecret.set')" == "true" ]] && ! confirm "Replace the existing Google OAuth client?"; then
  say "Keeping the existing Google OAuth client."
else
  open_url "$APP/settings"
  say "Follow the Google card on that page: it deep-links every Google Cloud console"
  say "step, in the order Google imposes, with the exact values and copy buttons."
  note "The redirect URI must be http://localhost:4317/api/google/callback — the card shows it."
  note "Enable ALL four APIs on the card (Tasks, Gmail, Drive, YouTube Data) or the first run 403s."
  GOOGLE_CLIENT_ID=""
  GOOGLE_CLIENT_SECRET=""
  ask GOOGLE_CLIENT_ID "Paste the OAuth client ID:"
  ask_secret GOOGLE_CLIENT_SECRET "Paste the OAuth client secret:"
  body=$(jq -n --arg i "$GOOGLE_CLIENT_ID" --arg s "$GOOGLE_CLIENT_SECRET" \
    '{google: {clientId: $i, clientSecret: $s}}')
  api PUT /api/config "$body"
  [[ "$_API_CODE" == "200" ]] && say "Google OAuth client saved." || warn "save failed (HTTP $_API_CODE)"
fi

# ── 4 · Google connect + verify ───────────────────────────────────────────
stage "Google sign-in"
api GET /api/google/status
GOOGLE_STATE="$(api_jq '.state // empty')"
if [[ "$GOOGLE_STATE" == "connected" ]] && ! confirm "Sign in to Google again anyway?"; then
  say "Google connection kept."
  note "Personal accounts re-auth about weekly — re-running this script lands here: choose to sign in again."
else
  api GET /api/google/connect
  if [[ "$_API_CODE" != "200" ]]; then
    warn "cannot start sign-in (HTTP $_API_CODE): $(api_jq '.error // empty')"
    SKIPPED+=("Google sign-in")
  else
    AUTH_URL="$(api_jq '.authUrl')"
    step "Sign in with the Google account that owns your Tasks, Gmail, Drive and YouTube."
    open_url "$AUTH_URL"
    note "Personal account: the 'unverified app' screen is expected — click Continue (small link, bottom left)."
    pause "Press Enter once you have completed the consent screen…"
    say "Waiting for Google to call back"
    CONNECTED=""
    for _ in $(seq 1 60); do
      api GET /api/google/status
      STATE="$(api_jq '.state // empty')"
      [[ "$STATE" == "connected" ]] && { CONNECTED=1; break; }
      printf '.'
      sleep 5
    done
    printf '\n'
    if [[ -n "$CONNECTED" ]]; then
      say "Connected."
      api POST /api/google/check
      say "Check my setup: $(printf '%s' "$_API_BODY" | jq -c .)"
    else
      warn "not connected after 5 minutes — check the Google card in Settings, then re-run."
      note "Failure symptoms are tabled in ONBOARDING.md → 'When something is wrong'."
      SKIPPED+=("Google sign-in verification")
    fi
  fi
fi

# ── 5 · Drive intake folder ───────────────────────────────────────────────
stage "Drive transcripts folder"
load_config
CUR_FOLDER="$(api_jq '.config.drive.folderName // empty')"
if [[ -n "$CUR_FOLDER" ]]; then
  say "Current folder: $CUR_FOLDER"
  confirm_folder="n"
  confirm "Pick a different folder?" && confirm_folder="y"
else
  say "No folder chosen yet — the app polls one Drive folder for transcripts."
  confirm_folder="y"
fi
if [[ "$confirm_folder" == "y" ]]; then
  open_url "$APP/settings"
  step "On the Drive transcripts card, click Choose folder and pick the folder your transcript service writes to."
  pause "Press Enter once saved…"
  api GET /api/config
  say "Folder now: $(api_jq '.config.drive.folderName // empty')"
fi
CUR_POLL="$(api_jq '.config.drive.pollIntervalMinutes // empty')"
ask POLL_MINUTES "Poll interval in minutes${CUR_POLL:+ [Enter keeps $CUR_POLL]}:"
[[ -z "$POLL_MINUTES" ]] && POLL_MINUTES="${CUR_POLL:-2}"
[[ "$POLL_MINUTES" =~ ^[0-9]+$ ]] || POLL_MINUTES=2
if (( POLL_MINUTES < 1 )); then POLL_MINUTES=1; fi
api PUT /api/config "$(jq -n --argjson n "$POLL_MINUTES" '{drive: {enabled: true, pollIntervalMinutes: $n}}')"
[[ "$_API_CODE" == "200" ]] && say "Drive polling on, every $POLL_MINUTES min." || warn "save failed (HTTP $_API_CODE)"

# ── 6 · Transcript smoke test (writes real Google data) ───────────────────
stage "Transcript smoke test"
say "This uploads the sample transcript and creates REAL Google Tasks and a REAL Gmail draft."
if ! confirm "Run the end-to-end smoke test now?"; then
  SKIPPED+=("Transcript smoke test")
  warn "skipped — run it later: upload the sample transcript, then Sync now in Settings."
else
  load_config
  FOLDER_ID="$(api_jq '.config.drive.folderId // empty')"
  [[ -n "$FOLDER_ID" ]] && open_url "https://drive.google.com/drive/folders/$FOLDER_ID" \
    || open_url "https://drive.google.com"
  step "Upload tests/fixtures/transcripts/sample-transcript.md to that folder (New → File upload)."
  pause "Press Enter once uploaded…"
  api POST /api/drive/sync
  CREATED="$(api_jq '.created // 0')"
  say "Sync created $CREATED run(s)."
  api GET "/api/runs?module=transcript&limit=1"
  RUN_ID="$(api_jq '.runs[0].id // empty')"
  if [[ "$CREATED" == "0" || -z "$RUN_ID" ]]; then
    warn "no new run to watch — either nothing was ingested (the ledger remembers every file id it has seen) or the file landed in a different folder."
    SKIPPED+=("Transcript smoke test verification")
  else
    say "Watching run $RUN_ID"
    for _ in $(seq 1 60); do
      api GET "/api/runs/$RUN_ID"
      RUN_STATUS="$(api_jq '.status')"
      case "$RUN_STATUS" in done|failed|skipped) break ;; esac
      printf '.'
      sleep 5
    done
    printf '\n'
    say "Run $RUN_ID → $RUN_STATUS"
    [[ "$RUN_STATUS" == "done" ]] && step "Confirm: Google Tasks list 'Meeting Followups' has 3 tasks; Gmail Drafts has 1 draft."
  fi
fi

# ── 7 · YouTube channels ──────────────────────────────────────────────────
stage "YouTube channels"
api GET /api/youtube/trends
EXISTING_CHANNELS="$(api_jq '.channels | length')"
if [[ "$EXISTING_CHANNELS" =~ ^[0-9]+$ ]] && (( EXISTING_CHANNELS > 0 )) \
  && confirm "Keep the $EXISTING_CHANNELS channel(s) already being tracked?"; then
  say "Channels kept."
else
  while true; do
    ask CHANNEL_URL "Channel URL (youtube.com/@name or /channel/UC…, empty to stop):"
    [[ -z "$CHANNEL_URL" ]] && break
    api POST /api/youtube/channels "$(jq -n --arg u "$CHANNEL_URL" '{url: $u}')"
    if [[ "$_API_CODE" == "201" ]]; then
      say "Tracking: $(api_jq '.channel.title')"
    else
      warn "$(api_jq '.error // "failed (HTTP '"$_API_CODE"')"')"
    fi
  done
fi

# ── 8 · YouTube Trends spreadsheet (creates a real Sheet) ─────────────────
stage "YouTube Trends spreadsheet"
api GET /api/youtube/trends
EXISTING_URL="$(api_jq '.spreadsheet.url // empty')"
if [[ -n "$EXISTING_URL" ]]; then
  say "Spreadsheet already exists."
  open_url "$EXISTING_URL"
else
  say "Creates a spreadsheet named 'YouTube Trends' in your Drive — one tab per channel, one row per video per day."
  if confirm "Create it now?"; then
    api POST /api/youtube/spreadsheet
    if [[ "$_API_CODE" == "201" ]]; then
      open_url "$(api_jq '.spreadsheet.url')"
      say "Created."
    elif [[ "$_API_CODE" == "409" ]]; then
      say "Already exists (someone created it moments ago)."
      open_url "$(api_jq '.spreadsheet.url // empty')"
    else
      warn "creation failed (HTTP $_API_CODE): $(api_jq '.error // empty')"
      SKIPPED+=("YouTube Trends spreadsheet")
    fi
  else
    SKIPPED+=("YouTube Trends spreadsheet")
  fi
fi

# ── 9 · Content Scout schedule ───────────────────────────────────────────
stage "Content Scout schedule"
api GET /api/content-scout
say "Current: $(printf '%s' "$_API_BODY" | jq -c '.settings // empty')"
if confirm "Keep the current schedule?"; then
  say "Schedule kept."
else
  ask SCOUT_TZ "IANA time zone:"
  ask SCOUT_DAILY "Daily scout time (HH:MM):"
  ask SCOUT_WDAY "Weekly discovery weekday (1=Mon…7=Sun):"
  ask SCOUT_WTIME "Weekly discovery time (HH:MM):"
  ask SCOUT_SIZE "Shortlist size (3–10):"
  CUR_SETTINGS="$(printf '%s' "$_API_BODY" | jq -c '.settings // {}')"
  SCOUT_TZ="${SCOUT_TZ:-$(printf '%s' "$CUR_SETTINGS" | jq -r '.timeZone // empty')}"
  SCOUT_DAILY="${SCOUT_DAILY:-$(printf '%s' "$CUR_SETTINGS" | jq -r '.dailyTime // "08:00"')}"
  SCOUT_WDAY="${SCOUT_WDAY:-$(printf '%s' "$CUR_SETTINGS" | jq -r '.weeklyDiscoveryDay // 1')}"
  SCOUT_WTIME="${SCOUT_WTIME:-$(printf '%s' "$CUR_SETTINGS" | jq -r '.weeklyDiscoveryTime // "09:00"')}"
  SCOUT_SIZE="${SCOUT_SIZE:-$(printf '%s' "$CUR_SETTINGS" | jq -r '.shortlistSize // 5')}"
  [[ "$SCOUT_WDAY" =~ ^[1-7]$ ]] || SCOUT_WDAY=1
  [[ "$SCOUT_SIZE" =~ ^[0-9]+$ ]] || SCOUT_SIZE=5
  if (( SCOUT_SIZE < 3 )); then SCOUT_SIZE=3; fi
  if (( SCOUT_SIZE > 10 )); then SCOUT_SIZE=10; fi
  body=$(jq -n --arg tz "$SCOUT_TZ" --arg d "$SCOUT_DAILY" --argjson wd "$SCOUT_WDAY" \
    --arg wt "$SCOUT_WTIME" --argjson sz "$SCOUT_SIZE" \
    '{timeZone: $tz, dailyTime: $d, weeklyDiscoveryDay: $wd, weeklyDiscoveryTime: $wt, shortlistSize: $sz}')
  api PATCH /api/content-scout/settings "$body"
  if [[ "$_API_CODE" == "200" ]]; then
    say "Schedule saved: daily $SCOUT_DAILY $SCOUT_TZ, discovery weekday $SCOUT_WDAY at $SCOUT_WTIME, shortlist $SCOUT_SIZE."
  else
    warn "save failed (HTTP $_API_CODE): $(api_jq '.error // empty')"
  fi
fi

# ── 10 · Content Scout sources ───────────────────────────────────────────
stage "Content Scout sources"
say "Recurring public sources the daily scout reads (rss feeds work best)."
while true; do
  confirm "Add a source?" || break
  ask SOURCE_ADAPTER "Adapter (rss|website):"
  ask SOURCE_LABEL "Label (e.g. Hacker News front page):"
  ask SOURCE_URL "Public URL:"
  [[ -z "$SOURCE_URL" ]] && break
  api POST /api/content-scout/sources \
    "$(jq -n --arg a "$SOURCE_ADAPTER" --arg l "$SOURCE_LABEL" --arg u "$SOURCE_URL" '{adapterId: $a, label: $l, url: $u}')"
  if [[ "$_API_CODE" == "200" || "$_API_CODE" == "201" ]]; then
    say "Source added."
  else
    warn "$(api_jq '.error // "failed (HTTP '"$_API_CODE"')"')"
  fi
done

# ── 11 · Meeting Brief Generator ──────────────────────────────────────────
stage "Meeting Brief Generator"
warn "Heads-up: as shipped, this Module cannot RUN — no calendar provider is wired in, and"
warn "external-guest enrichment needs six providers the server does not have. This stage"
warn "records your configuration only; unlocking Runs needs a code change (see the smoke report)."
if confirm "Configure Meeting Brief settings anyway?"; then
  ask INTERNAL_DOMAINS "Internal domains, comma-separated (e.g. found42.com):"
  if [[ -n "$INTERNAL_DOMAINS" ]]; then
    domains=()
    IFS=',' read -r -a _parts <<< "$INTERNAL_DOMAINS"
    for d in "${_parts[@]}"; do d="$(printf '%s' "$d" | sed 's/^ *//; s/ *$//')"; [[ -n "$d" ]] && domains+=("$d"); done
    body=$(jq -n '$ARGS.positional | {internalDomains: .}' --args "${domains[@]}")
    api PUT /api/meeting-brief/config "$body"
    [[ "$_API_CODE" == "200" ]] && say "Internal domains saved." || warn "save failed (HTTP $_API_CODE)"
  fi
  if confirm "Connect HubSpot now?"; then
    open_url "https://app.hubspot.com/private-apps"
    step "Create a private app with read access to companies and contacts, then copy its token (pat-na1-…)."
    ask_secret HUBSPOT_TOKEN "Paste the HubSpot private-app token:"
    api POST /api/meeting-brief/hubspot/connect "$(jq -n --arg t "$HUBSPOT_TOKEN" '{token: $t}')"
    api POST /api/meeting-brief/hubspot/check
    say "HubSpot check: $(printf '%s' "$_API_BODY" | jq -c .)"
  else
    SKIPPED+=("HubSpot connection")
  fi
  if confirm "Connect the guest-profile provider now?"; then
    ask GP_ENDPOINT "Guest-profile service endpoint URL:"
    ask_secret GP_KEY "Guest-profile API key:"
    api POST /api/meeting-brief/guest-profile/connect \
      "$(jq -n --arg e "$GP_ENDPOINT" --arg k "$GP_KEY" '{endpoint: $e, apiKey: $k}')"
    api POST /api/meeting-brief/guest-profile/check
    say "Guest-profile check: $(printf '%s' "$_API_BODY" | jq -c .)"
  else
    SKIPPED+=("Guest-profile connection")
  fi
else
  SKIPPED+=("Meeting Brief Generator settings")
fi

# ── 12 · Final check ──────────────────────────────────────────────────────
stage "Final check"
api GET /api/health
say "App: $( [[ "$_API_CODE" == "200" ]] && printf 'healthy' || printf 'UNHEALTHY' ) at $APP"
load_config
say "Provider: $(api_jq '.config.provider') / $(api_jq '.config.model') · key set: $(api_jq '.config.apiKey.set')"
say "Google client: $(api_jq '.config.google.clientSecret.set' | sed 's/true/set/; s/false/unset/')"
say "Drive folder: $(api_jq '.config.drive.folderName // "none"') (polling $(api_jq '.config.drive.enabled' | sed 's/true/on/; s/false/off/'))"
api GET /api/google/status
say "Google connection: $(api_jq '.state // "unknown"')"
api GET /api/youtube/trends
say "YouTube Trends sheet: $(api_jq '.spreadsheet.url // "none"')"
api GET /api/content-scout
say "Content Scout: $(printf '%s' "$_API_BODY" | jq -r '.sourceTargets | length') source target(s)"
api GET /api/meeting-brief/config
say "Meeting Brief: $(printf '%s' "$_API_BODY" | jq -c '{internalDomains: (.internalDomains | length), hubspot: .hubspot.state}')"
say ""
say "Open the app: $APP"
note "Anything misbehave? ONBOARDING.md → 'When something is wrong' names the fix."

finish
